spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/triprider?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${DB_USERNAME:tripuser}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate          # 운영 권장 (스키마는 Flyway로)
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB

  flyway:
    enabled: true                 # 스키마 관리 도입 권장
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 316137395420-ig547fms4sva0jaoup5odgldfqhf36o4.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "https://api.yourdomain.com/login/oauth2/code/google"
          kakao:
            client-id: 471ee3eec0b9d8a5fc4eb86fb849e524
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "https://api.yourdomain.com/login/oauth2/code/kakao"
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

course:
  # EC2에서는 외부 경로 또는 S3로 전환 권장
  path: classpath:/course

tourapi:
  base-url: "https://apis.data.go.kr/B551011/KorService2"
  service-key: "iQo2RqyJxO6Aq9UoLG3zi4v597yqgmlux9hm4Rr0GJ1FtlyXr0wEQAeO4eJWr6x7u2tbn3ZoVyzH1/bhUWRZ6g=="

weather:
  api:
    base-url: "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
    service-key: "B9lcEXU87CZ1bElz2TDsg24h3MrLRNIvSaS3U3tJadZevbVF15IegPFce577ni1sQSNvFEueuKIwO0wQcAd4tQ=="

server.port: 8080
logging.level.org.hibernate.SQL: info
